/*  Vector field function and events for Radau integrator.
  This code was automatically generated by PyDSTool, but may be modified by hand. */

#include <math.h>
#include <Python.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "events.h"
#include "maxmin.h"
#include "signum.h"
#include "vfield.h"

extern double *gICs;
extern double **gBds;
extern double globalt0;

static double pi = 3.1415926535897931;

double signum(double x)
{
  if (x<0) {
    return -1;
  }
  else if (x==0) {
    return 0;
  }
  else if (x>0) {
    return 1;
  }
  else {
    /* must be that x is Not-a-Number */
    return x;
  }
}


/* Variable, aux variable, parameter, and input definitions: */ 
#define N	p_[0]
#define beta	p_[1]
#define delta	p_[2]
#define im	p_[3]
#define mu	p_[4]
#define sigma	p_[5]
#define I_1	Y_[0]
#define I_12	Y_[1]
#define I_123	Y_[2]
#define I_1234	Y_[3]
#define I_124	Y_[4]
#define I_1243	Y_[5]
#define I_13	Y_[6]
#define I_132	Y_[7]
#define I_134	Y_[8]
#define I_1342	Y_[9]
#define I_14	Y_[10]
#define I_142	Y_[11]
#define I_143	Y_[12]
#define I_2	Y_[13]
#define I_21	Y_[14]
#define I_23	Y_[15]
#define I_231	Y_[16]
#define I_234	Y_[17]
#define I_2341	Y_[18]
#define I_24	Y_[19]
#define I_241	Y_[20]
#define I_243	Y_[21]
#define I_3	Y_[22]
#define I_31	Y_[23]
#define I_32	Y_[24]
#define I_34	Y_[25]
#define I_341	Y_[26]
#define I_342	Y_[27]
#define I_4	Y_[28]
#define I_41	Y_[29]
#define I_42	Y_[30]
#define I_43	Y_[31]
#define R_1	Y_[32]
#define R_12	Y_[33]
#define R_123	Y_[34]
#define R_1234	Y_[35]
#define R_124	Y_[36]
#define R_13	Y_[37]
#define R_134	Y_[38]
#define R_14	Y_[39]
#define R_2	Y_[40]
#define R_23	Y_[41]
#define R_234	Y_[42]
#define R_24	Y_[43]
#define R_3	Y_[44]
#define R_34	Y_[45]
#define R_4	Y_[46]
#define S	Y_[47]


double __maxof2(double e1_, double e2_, double *p_, double *wk_, double *xv_);
double __maxof3(double e1_, double e2_, double e3_, double *p_, double *wk_, double *xv_);
double __maxof4(double e1_, double e2_, double e3_, double e4_, double *p_, double *wk_, double *xv_);
double __minof2(double e1_, double e2_, double *p_, double *wk_, double *xv_);
double __minof3(double e1_, double e2_, double e3_, double *p_, double *wk_, double *xv_);
double __minof4(double e1_, double e2_, double e3_, double e4_, double *p_, double *wk_, double *xv_);
double __rhs_if(int cond_, double e1_, double e2_, double *p_, double *wk_, double *xv_);
double getbound(char *name, int which_bd, double *p_, double *wk_, double *xv_);
double globalindepvar(double t, double *p_, double *wk_, double *xv_);
double initcond(char *varname, double *p_, double *wk_, double *xv_);
double m1(double __t__, double *p_, double *wk_, double *xv_);
double m2(double __t__, double *p_, double *wk_, double *xv_);
double m3(double __t__, double *p_, double *wk_, double *xv_);
int getindex(char *name, double *p_, double *wk_, double *xv_);
int heav(double x_, double *p_, double *wk_, double *xv_);

int N_EVENTS = 0;
void assignEvents(EvFunType *events){
 
}

void auxvars(unsigned, unsigned, double, double*, double*, double*, unsigned, double*, unsigned, double*);
void jacobian(unsigned, unsigned, double, double*, double*, double**, unsigned, double*, unsigned, double*);
void jacobianParam(unsigned, unsigned, double, double*, double*, double**, unsigned, double*, unsigned, double*);
int N_AUXVARS = 0;


int N_EXTINPUTS = 0;


void vfieldfunc(unsigned n_, unsigned np_, double t, double *Y_, double *p_, double *f_, unsigned wkn_, double *wk_, unsigned xvn_, double *xv_){

f_[0] = m1(t, p_, wk_, xv_)+beta*S*(I_1+I_21+I_31+I_41+I_231+I_241+I_341+I_2341)-sigma*I_1-mu*I_1;
f_[1] = beta*delta*R_1*(I_2+I_12+I_32+I_42+I_132+I_142+I_342+I_1342)-sigma*I_12-mu*I_12;
f_[2] = beta*delta*R_12*(I_3+I_13+I_23+I_43+I_123+I_143+I_243+I_1243)-sigma*I_123-mu*I_123;
f_[3] = beta*delta*R_123*(I_4+I_14+I_24+I_34+I_124+I_134+I_234+I_1234)-sigma*I_1234-mu*I_1234;
f_[4] = beta*delta*R_12*(I_4+I_14+I_24+I_34+I_124+I_134+I_234+I_1234)-sigma*I_124-mu*I_124;
f_[5] = beta*delta*R_124*(I_3+I_13+I_23+I_43+I_123+I_143+I_243+I_1243)-sigma*I_1243-mu*I_1243;
f_[6] = beta*delta*R_1*(I_3+I_13+I_23+I_43+I_123+I_143+I_243+I_1243)-sigma*I_13-mu*I_13;
f_[7] = beta*delta*R_13*(I_2+I_12+I_32+I_42+I_132+I_142+I_342+I_1342)-sigma*I_132-mu*I_132;
f_[8] = beta*delta*R_13*(I_4+I_14+I_24+I_34+I_124+I_134+I_234+I_1234)-sigma*I_134-mu*I_134;
f_[9] = beta*delta*R_134*(I_2+I_12+I_32+I_42+I_132+I_142+I_342+I_1342)-sigma*I_1342-mu*I_1342;
f_[10] = beta*delta*R_1*(I_4+I_14+I_24+I_34+I_124+I_134+I_234+I_1234)-sigma*I_14-mu*I_14;
f_[11] = beta*delta*R_14*(I_2+I_12+I_32+I_42+I_132+I_142+I_342+I_1342)-sigma*I_142-mu*I_142;
f_[12] = beta*delta*R_14*(I_3+I_13+I_23+I_43+I_123+I_143+I_243+I_1243)-sigma*I_143-mu*I_143;
f_[13] = m2(t, p_, wk_, xv_)+beta*S*(I_2+I_12+I_32+I_42+I_132+I_142+I_342+I_1342)-sigma*I_2-mu*I_2;
f_[14] = beta*delta*R_2*(I_1+I_21+I_31+I_41+I_231+I_241+I_341+I_2341)-sigma*I_21-mu*I_21;
f_[15] = beta*delta*R_2*(I_3+I_13+I_23+I_43+I_123+I_143+I_243+I_1243)-sigma*I_23-mu*I_23;
f_[16] = beta*delta*R_23*(I_1+I_21+I_31+I_41+I_231+I_241+I_341+I_2341)-sigma*I_231-mu*I_231;
f_[17] = beta*delta*R_23*(I_4+I_14+I_24+I_34+I_124+I_134+I_234+I_1234)-sigma*I_234-mu*I_234;
f_[18] = beta*delta*R_234*(I_1+I_21+I_31+I_41+I_231+I_241+I_341+I_2341)-sigma*I_2341-mu*I_2341;
f_[19] = beta*delta*R_2*(I_4+I_14+I_24+I_34+I_124+I_134+I_234+I_1234)-sigma*I_24-mu*I_24;
f_[20] = beta*delta*R_24*(I_1+I_21+I_31+I_41+I_231+I_241+I_341+I_2341)-sigma*I_241-mu*I_241;
f_[21] = beta*delta*R_24*(I_3+I_13+I_23+I_43+I_123+I_143+I_243+I_1243)-sigma*I_243-mu*I_243;
f_[22] = m3(t, p_, wk_, xv_)+beta*S*(I_3+I_13+I_23+I_43+I_123+I_143+I_243+I_1243)-sigma*I_3-mu*I_3;
f_[23] = beta*delta*R_3*(I_1+I_21+I_31+I_41+I_231+I_241+I_341+I_2341)-sigma*I_31-mu*I_31;
f_[24] = beta*delta*R_3*(I_2+I_12+I_32+I_42+I_132+I_142+I_342+I_1342)-sigma*I_32-mu*I_32;
f_[25] = beta*delta*R_3*(I_4+I_14+I_24+I_34+I_124+I_134+I_234+I_1234)-sigma*I_34-mu*I_34;
f_[26] = beta*delta*R_34*(I_1+I_21+I_31+I_41+I_231+I_241+I_341+I_2341)-sigma*I_341-mu*I_341;
f_[27] = beta*delta*R_34*(I_2+I_12+I_32+I_42+I_132+I_142+I_342+I_1342)-sigma*I_342-mu*I_342;
f_[28] = beta*S*(I_4+I_14+I_24+I_34+I_124+I_134+I_234+I_1234)-sigma*I_4-mu*I_4;
f_[29] = beta*delta*R_4*(I_1+I_21+I_31+I_41+I_231+I_241+I_341+I_2341)-sigma*I_41-mu*I_41;
f_[30] = beta*delta*R_4*(I_2+I_12+I_32+I_42+I_132+I_142+I_342+I_1342)-sigma*I_42-mu*I_42;
f_[31] = beta*delta*R_4*(I_3+I_13+I_23+I_43+I_123+I_143+I_243+I_1243)-sigma*I_43-mu*I_43;
f_[32] = sigma*I_1-beta*delta*R_1*(I_2+I_12+I_32+I_42+I_132+I_142+I_342+I_1342+I_3+I_13+I_23+I_43+I_123+I_143+I_243+I_1243+I_4+I_14+I_24+I_34+I_124+I_134+I_234+I_1234)-mu*R_1;
f_[33] = sigma*(I_12+I_21)-beta*delta*R_12*(I_3+I_13+I_23+I_43+I_123+I_143+I_243+I_1243+I_4+I_14+I_24+I_34+I_124+I_134+I_234+I_1234)-mu*R_12;
f_[34] = sigma*(I_123+I_132+I_231)-beta*delta*R_123*(I_4+I_14+I_24+I_34+I_124+I_134+I_234+I_1234)-mu*R_123;
f_[35] = sigma*(I_1234+I_1243+I_1342+I_2341)-mu*R_1234;
f_[36] = sigma*(I_124+I_241+I_142)-beta*delta*R_124*(I_3+I_13+I_23+I_43+I_123+I_143+I_243+I_1243)-mu*R_124;
f_[37] = sigma*(I_13+I_31)-beta*delta*R_13*(I_2+I_12+I_32+I_42+I_132+I_142+I_342+I_1342+I_4+I_14+I_24+I_34+I_124+I_134+I_234+I_1234)-mu*R_13;
f_[38] = sigma*(I_134+I_341+I_143)-beta*delta*R_134*(I_2+I_12+I_32+I_42+I_132+I_142+I_342+I_1342)-mu*R_134;
f_[39] = sigma*(I_14+I_41)-beta*delta*R_14*(I_2+I_12+I_32+I_42+I_132+I_142+I_342+I_1342+I_3+I_13+I_23+I_43+I_123+I_143+I_243+I_1243)-mu*R_14;
f_[40] = sigma*I_2-beta*delta*R_2*(I_1+I_21+I_31+I_41+I_231+I_241+I_341+I_2341+I_3+I_13+I_23+I_43+I_123+I_143+I_243+I_1243+I_4+I_14+I_24+I_34+I_124+I_134+I_234+I_1234)-mu*R_2;
f_[41] = sigma*(I_23+I_32)-beta*delta*R_23*(I_1+I_21+I_31+I_41+I_231+I_241+I_341+I_2341+I_4+I_14+I_24+I_34+I_124+I_134+I_234+I_1234)-mu*R_23;
f_[42] = sigma*(I_234+I_342+I_243)-beta*delta*R_234*(I_2+I_12+I_32+I_42+I_132+I_142+I_342+I_1342)-mu*R_134;
f_[43] = sigma*(I_24+I_42)-beta*delta*R_24*(I_1+I_21+I_31+I_41+I_231+I_241+I_341+I_2341+I_3+I_13+I_23+I_43+I_123+I_143+I_243+I_1243)-mu*R_24;
f_[44] = sigma*I_3-beta*delta*R_3*(I_1+I_21+I_31+I_41+I_231+I_241+I_341+I_2341+I_2+I_12+I_32+I_42+I_132+I_142+I_342+I_1342+I_4+I_14+I_24+I_34+I_124+I_134+I_234+I_1234)-mu*R_3;
f_[45] = sigma*(I_34+I_43)-beta*delta*R_34*(I_1+I_21+I_31+I_41+I_231+I_241+I_341+I_2341+I_2+I_12+I_32+I_42+I_132+I_142+I_342+I_1342)-mu*R_34;
f_[46] = sigma*I_4-beta*delta*R_4*(I_1+I_21+I_31+I_41+I_231+I_241+I_341+I_2341+I_2+I_12+I_32+I_42+I_132+I_142+I_342+I_1342+I_3+I_13+I_23+I_43+I_123+I_143+I_243+I_1243)-mu*R_4;
f_[47] = -beta*S*(I_1+I_21+I_31+I_41+I_231+I_241+I_341+I_2341+I_2+I_12+I_32+I_42+I_132+I_142+I_342+I_1342+I_3+I_13+I_23+I_43+I_123+I_143+I_243+I_1243+I_4+I_14+I_24+I_34+I_124+I_134+I_234+I_1234)+mu*N-mu*S;

}




double __maxof2(double e1_, double e2_, double *p_, double *wk_, double *xv_) {
if (e1_ > e2_) {return e1_;} else {return e2_;};
}


double __maxof3(double e1_, double e2_, double e3_, double *p_, double *wk_, double *xv_) {
double temp_;
if (e1_ > e2_) {temp_ = e1_;} else {temp_ = e2_;};
if (e3_ > temp_) {return e3_;} else {return temp_;};
}


double __maxof4(double e1_, double e2_, double e3_, double e4_, double *p_, double *wk_, double *xv_) {
double temp_;
if (e1_ > e2_) {temp_ = e1_;} else {temp_ = e2_;};
if (e3_ > temp_) {temp_ = e3_;};
if (e4_ > temp_) {return e4_;} else {return temp_;};
}


double __minof2(double e1_, double e2_, double *p_, double *wk_, double *xv_) {
if (e1_ < e2_) {return e1_;} else {return e2_;};
}


double __minof3(double e1_, double e2_, double e3_, double *p_, double *wk_, double *xv_) {
double temp_;
if (e1_ < e2_) {temp_ = e1_;} else {temp_ = e2_;};
if (e3_ < temp_) {return e3_;} else {return temp_;};
}


double __minof4(double e1_, double e2_, double e3_, double e4_, double *p_, double *wk_, double *xv_) {
double temp_;
if (e1_ < e2_) {temp_ = e1_;} else {temp_ = e2_;};
if (e3_ < temp_) {temp_ = e3_;};
if (e4_ < temp_) {return e4_;} else {return temp_;};
}


double __rhs_if(int cond_, double e1_, double e2_, double *p_, double *wk_, double *xv_) {
  if (cond_) {return e1_;} else {return e2_;};
}


double getbound(char *name, int which_bd, double *p_, double *wk_, double *xv_) {
  return gBds[which_bd][getindex(name, p_, wk_, xv_)];
}


double globalindepvar(double t, double *p_, double *wk_, double *xv_) {
  return globalt0+t;
}


double initcond(char *varname, double *p_, double *wk_, double *xv_) {

  if (strcmp(varname, "I_1")==0)
	return gICs[0];
  else if (strcmp(varname, "I_12")==0)
	return gICs[1];
  else if (strcmp(varname, "I_123")==0)
	return gICs[2];
  else if (strcmp(varname, "I_1234")==0)
	return gICs[3];
  else if (strcmp(varname, "I_124")==0)
	return gICs[4];
  else if (strcmp(varname, "I_1243")==0)
	return gICs[5];
  else if (strcmp(varname, "I_13")==0)
	return gICs[6];
  else if (strcmp(varname, "I_132")==0)
	return gICs[7];
  else if (strcmp(varname, "I_134")==0)
	return gICs[8];
  else if (strcmp(varname, "I_1342")==0)
	return gICs[9];
  else if (strcmp(varname, "I_14")==0)
	return gICs[10];
  else if (strcmp(varname, "I_142")==0)
	return gICs[11];
  else if (strcmp(varname, "I_143")==0)
	return gICs[12];
  else if (strcmp(varname, "I_2")==0)
	return gICs[13];
  else if (strcmp(varname, "I_21")==0)
	return gICs[14];
  else if (strcmp(varname, "I_23")==0)
	return gICs[15];
  else if (strcmp(varname, "I_231")==0)
	return gICs[16];
  else if (strcmp(varname, "I_234")==0)
	return gICs[17];
  else if (strcmp(varname, "I_2341")==0)
	return gICs[18];
  else if (strcmp(varname, "I_24")==0)
	return gICs[19];
  else if (strcmp(varname, "I_241")==0)
	return gICs[20];
  else if (strcmp(varname, "I_243")==0)
	return gICs[21];
  else if (strcmp(varname, "I_3")==0)
	return gICs[22];
  else if (strcmp(varname, "I_31")==0)
	return gICs[23];
  else if (strcmp(varname, "I_32")==0)
	return gICs[24];
  else if (strcmp(varname, "I_34")==0)
	return gICs[25];
  else if (strcmp(varname, "I_341")==0)
	return gICs[26];
  else if (strcmp(varname, "I_342")==0)
	return gICs[27];
  else if (strcmp(varname, "I_4")==0)
	return gICs[28];
  else if (strcmp(varname, "I_41")==0)
	return gICs[29];
  else if (strcmp(varname, "I_42")==0)
	return gICs[30];
  else if (strcmp(varname, "I_43")==0)
	return gICs[31];
  else if (strcmp(varname, "R_1")==0)
	return gICs[32];
  else if (strcmp(varname, "R_12")==0)
	return gICs[33];
  else if (strcmp(varname, "R_123")==0)
	return gICs[34];
  else if (strcmp(varname, "R_1234")==0)
	return gICs[35];
  else if (strcmp(varname, "R_124")==0)
	return gICs[36];
  else if (strcmp(varname, "R_13")==0)
	return gICs[37];
  else if (strcmp(varname, "R_134")==0)
	return gICs[38];
  else if (strcmp(varname, "R_14")==0)
	return gICs[39];
  else if (strcmp(varname, "R_2")==0)
	return gICs[40];
  else if (strcmp(varname, "R_23")==0)
	return gICs[41];
  else if (strcmp(varname, "R_234")==0)
	return gICs[42];
  else if (strcmp(varname, "R_24")==0)
	return gICs[43];
  else if (strcmp(varname, "R_3")==0)
	return gICs[44];
  else if (strcmp(varname, "R_34")==0)
	return gICs[45];
  else if (strcmp(varname, "R_4")==0)
	return gICs[46];
  else if (strcmp(varname, "S")==0)
	return gICs[47];
  else {
	fprintf(stderr, "Invalid variable name %s for initcond call\n", varname);
	return 0.0/0.0;
	}
}


double m1(double __t__, double *p_, double *wk_, double *xv_) {


return (__t__>5&&__t__<=20)*im ;

}


double m2(double __t__, double *p_, double *wk_, double *xv_) {


return (__t__>10&&__t__<=25)*im ;

}


double m3(double __t__, double *p_, double *wk_, double *xv_) {


return (__t__>15&&__t__<=30)*im ;

}


int getindex(char *name, double *p_, double *wk_, double *xv_) {

  if (strcmp(name, "I_1")==0)
	return 0;
  else if (strcmp(name, "I_12")==0)
	return 1;
  else if (strcmp(name, "I_123")==0)
	return 2;
  else if (strcmp(name, "I_1234")==0)
	return 3;
  else if (strcmp(name, "I_124")==0)
	return 4;
  else if (strcmp(name, "I_1243")==0)
	return 5;
  else if (strcmp(name, "I_13")==0)
	return 6;
  else if (strcmp(name, "I_132")==0)
	return 7;
  else if (strcmp(name, "I_134")==0)
	return 8;
  else if (strcmp(name, "I_1342")==0)
	return 9;
  else if (strcmp(name, "I_14")==0)
	return 10;
  else if (strcmp(name, "I_142")==0)
	return 11;
  else if (strcmp(name, "I_143")==0)
	return 12;
  else if (strcmp(name, "I_2")==0)
	return 13;
  else if (strcmp(name, "I_21")==0)
	return 14;
  else if (strcmp(name, "I_23")==0)
	return 15;
  else if (strcmp(name, "I_231")==0)
	return 16;
  else if (strcmp(name, "I_234")==0)
	return 17;
  else if (strcmp(name, "I_2341")==0)
	return 18;
  else if (strcmp(name, "I_24")==0)
	return 19;
  else if (strcmp(name, "I_241")==0)
	return 20;
  else if (strcmp(name, "I_243")==0)
	return 21;
  else if (strcmp(name, "I_3")==0)
	return 22;
  else if (strcmp(name, "I_31")==0)
	return 23;
  else if (strcmp(name, "I_32")==0)
	return 24;
  else if (strcmp(name, "I_34")==0)
	return 25;
  else if (strcmp(name, "I_341")==0)
	return 26;
  else if (strcmp(name, "I_342")==0)
	return 27;
  else if (strcmp(name, "I_4")==0)
	return 28;
  else if (strcmp(name, "I_41")==0)
	return 29;
  else if (strcmp(name, "I_42")==0)
	return 30;
  else if (strcmp(name, "I_43")==0)
	return 31;
  else if (strcmp(name, "R_1")==0)
	return 32;
  else if (strcmp(name, "R_12")==0)
	return 33;
  else if (strcmp(name, "R_123")==0)
	return 34;
  else if (strcmp(name, "R_1234")==0)
	return 35;
  else if (strcmp(name, "R_124")==0)
	return 36;
  else if (strcmp(name, "R_13")==0)
	return 37;
  else if (strcmp(name, "R_134")==0)
	return 38;
  else if (strcmp(name, "R_14")==0)
	return 39;
  else if (strcmp(name, "R_2")==0)
	return 40;
  else if (strcmp(name, "R_23")==0)
	return 41;
  else if (strcmp(name, "R_234")==0)
	return 42;
  else if (strcmp(name, "R_24")==0)
	return 43;
  else if (strcmp(name, "R_3")==0)
	return 44;
  else if (strcmp(name, "R_34")==0)
	return 45;
  else if (strcmp(name, "R_4")==0)
	return 46;
  else if (strcmp(name, "S")==0)
	return 47;
  else if (strcmp(name, "N")==0)
	return 48;
  else if (strcmp(name, "beta")==0)
	return 49;
  else if (strcmp(name, "delta")==0)
	return 50;
  else if (strcmp(name, "im")==0)
	return 51;
  else if (strcmp(name, "mu")==0)
	return 52;
  else if (strcmp(name, "sigma")==0)
	return 53;
  else {
	fprintf(stderr, "Invalid name %s for getindex call\n", name);
	return 0.0/0.0;
	}
}


int heav(double x_, double *p_, double *wk_, double *xv_) {
  if (x_>0.0) {return 1;} else {return 0;}
}

void auxvars(unsigned n_, unsigned np_, double t, double *Y_, double *p_, double *f_, unsigned wkn_, double *wk_, unsigned xvn_, double *xv_){


}


void massMatrix(unsigned n_, unsigned np_, double t, double *Y_, double *p_, double **f_, unsigned wkn_, double *wk_, unsigned xvn_, double *xv_) {
}

void jacobian(unsigned n_, unsigned np_, double t, double *Y_, double *p_, double **f_, unsigned wkn_, double *wk_, unsigned xvn_, double *xv_) {
}

void jacobianParam(unsigned n_, unsigned np_, double t, double *Y_, double *p_, double **f_, unsigned wkn_, double *wk_, unsigned xvn_, double *xv_) {
}
